-- AlterEnum
BEGIN;
CREATE TYPE "StatusOperation_new" AS ENUM ('PENDING', 'INPROGRESS', 'TO_APPROVED', 'APPROVED', 'REJECTED', 'COMPLETED', 'CANCELED');
ALTER TABLE "public"."Operation" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Operation" ALTER COLUMN "status" TYPE "StatusOperation_new" USING ("status"::text::"StatusOperation_new");
ALTER TYPE "StatusOperation" RENAME TO "StatusOperation_old";
ALTER TYPE "StatusOperation_new" RENAME TO "StatusOperation";
DROP TYPE "public"."StatusOperation_old";
ALTER TABLE "Operation" ALTER COLUMN "status" SET DEFAULT 'PENDING';
COMMIT;

-- DropForeignKey
ALTER TABLE "public"."Site" DROP CONSTRAINT "Site_id_user_fkey";

-- DropForeignKey
ALTER TABLE "public"."User" DROP CONSTRAINT "User_id_site_fkey";

-- AlterTable
ALTER TABLE "Bill" ADD COLUMN     "dateEnd_group" DATE,
ADD COLUMN     "dateStart_group" DATE,
ADD COLUMN     "timeEnd_group" TEXT,
ADD COLUMN     "timeStart_group" TEXT,
ALTER COLUMN "total_bill" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "total_paysheet" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "number_of_hours" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "HOD" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "HON" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "HED" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "HEN" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "HFOD" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "HFON" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "HFED" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "HFEN" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "FAC_HOD" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "FAC_HON" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "FAC_HED" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "FAC_HEN" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "FAC_HFOD" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "FAC_HFON" SET DATA TYPE DECIMAL(4,3),
ALTER COLUMN "FAC_HFED" SET DATA TYPE DECIMAL(4,3),
ALTER COLUMN "FAC_HFEN" SET DATA TYPE DECIMAL(4,3),
ALTER COLUMN "group_hours" SET DATA TYPE DECIMAL(15,2);

-- AlterTable
ALTER TABLE "BillDetail" ALTER COLUMN "pay_unit" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "pay_rate" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "total_bill" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "total_paysheet" SET DATA TYPE DECIMAL(15,3);

-- AlterTable
ALTER TABLE "Site" ALTER COLUMN "id_user" SET NOT NULL;

-- AlterTable
ALTER TABLE "Tariff" ADD COLUMN     "isSpecial" "YES_NO" NOT NULL DEFAULT 'NO',
ALTER COLUMN "paysheet_tariff" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "facturation_tariff" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "pay_units" SET DATA TYPE DECIMAL(5,3),
ALTER COLUMN "agreed_hours" SET DATA TYPE DECIMAL(5,3),
ALTER COLUMN "OD" SET DATA TYPE DECIMAL(4,3),
ALTER COLUMN "ON" SET DATA TYPE DECIMAL(4,3),
ALTER COLUMN "ED" SET DATA TYPE DECIMAL(4,3),
ALTER COLUMN "EN" SET DATA TYPE DECIMAL(4,3),
ALTER COLUMN "FOD" SET DATA TYPE DECIMAL(4,3),
ALTER COLUMN "FON" SET DATA TYPE DECIMAL(4,3),
ALTER COLUMN "FED" SET DATA TYPE DECIMAL(4,3),
ALTER COLUMN "FEN" SET DATA TYPE DECIMAL(4,3),
ALTER COLUMN "FAC_OD" SET DATA TYPE DECIMAL(4,3),
ALTER COLUMN "FAC_ON" SET DATA TYPE DECIMAL(4,3),
ALTER COLUMN "FAC_ED" SET DATA TYPE DECIMAL(4,3),
ALTER COLUMN "FAC_EN" SET DATA TYPE DECIMAL(4,3),
ALTER COLUMN "FAC_FOD" SET DATA TYPE DECIMAL(4,3),
ALTER COLUMN "FAC_FON" SET DATA TYPE DECIMAL(4,3),
ALTER COLUMN "FAC_FED" SET DATA TYPE DECIMAL(4,3),
ALTER COLUMN "FAC_FEN" SET DATA TYPE DECIMAL(4,3);

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "id_site" SET NOT NULL;

-- CreateTable
CREATE TABLE "OperationConfirmation" (
    "id" SERIAL NOT NULL,
    "id_operation" INTEGER NOT NULL,
    "ipAddress" TEXT,
    "device" TEXT,
    "observation" TEXT,
    "confirmedAt" TIMESTAMP(3),

    CONSTRAINT "OperationConfirmation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Token" (
    "id" SERIAL NOT NULL,
    "id_confirmation" INTEGER NOT NULL,
    "token" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Token_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "OperationConfirmation_id_operation_key" ON "OperationConfirmation"("id_operation");

-- CreateIndex
CREATE UNIQUE INDEX "Token_token_key" ON "Token"("token");

-- AddForeignKey
ALTER TABLE "User" ADD CONSTRAINT "User_id_site_fkey" FOREIGN KEY ("id_site") REFERENCES "Site"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Site" ADD CONSTRAINT "Site_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OperationConfirmation" ADD CONSTRAINT "OperationConfirmation_id_operation_fkey" FOREIGN KEY ("id_operation") REFERENCES "Operation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Token" ADD CONSTRAINT "Token_id_confirmation_fkey" FOREIGN KEY ("id_confirmation") REFERENCES "OperationConfirmation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
