-- AlterTable
ALTER TABLE "Tariff" ALTER COLUMN "FAC_ED" DROP DEFAULT,
ALTER COLUMN "FAC_EN" DROP DEFAULT,
ALTER COLUMN "FAC_FED" DROP DEFAULT,
ALTER COLUMN "FAC_FEN" DROP DEFAULT,
ALTER COLUMN "FAC_FOD" DROP DEFAULT,
ALTER COLUMN "FAC_FON" DROP DEFAULT,
ALTER COLUMN "FAC_OD" DROP DEFAULT,
ALTER COLUMN "FAC_ON" DROP DEFAULT;
