-- CreateEnum
CREATE TYPE "ClientEmailType" AS ENUM ('LIQUIDATION', 'SUPERVISOR');

-- DropForeignKey
ALTER TABLE "public"."Site" DROP CONSTRAINT "Site_id_user_fkey";

-- DropForeignKey
ALTER TABLE "public"."User" DROP CONSTRAINT "User_id_site_fkey";

-- AlterTable
ALTER TABLE "Bill" ALTER COLUMN "FAC_HFON" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "FAC_HFED" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "FAC_HFEN" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "group_hours" SET DATA TYPE DECIMAL(15,3);

-- AlterTable
ALTER TABLE "Site" ALTER COLUMN "id_user" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Tariff" ALTER COLUMN "pay_units" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "agreed_hours" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "OD" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "ON" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "ED" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "EN" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "FOD" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "FON" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "FED" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "FEN" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "FAC_OD" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "FAC_ON" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "FAC_ED" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "FAC_EN" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "FAC_FOD" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "FAC_FON" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "FAC_FED" SET DATA TYPE DECIMAL(15,3),
ALTER COLUMN "FAC_FEN" SET DATA TYPE DECIMAL(15,3);

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "id_site" DROP NOT NULL;

-- CreateTable
CREATE TABLE "ClientEmail" (
    "id" SERIAL NOT NULL,
    "id_client" INTEGER NOT NULL,
    "email" TEXT NOT NULL,
    "type" "ClientEmailType" NOT NULL,
    "name" TEXT,
    "status" "StatusActivation" NOT NULL DEFAULT 'ACTIVE',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ClientEmail_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "ClientEmail_id_client_idx" ON "ClientEmail"("id_client");

-- CreateIndex
CREATE INDEX "ClientEmail_type_idx" ON "ClientEmail"("type");

-- CreateUniqueIndex
CREATE UNIQUE INDEX "ClientEmail_id_client_email_type_key" ON "ClientEmail"("id_client", "email", "type");

-- AddForeignKey
ALTER TABLE "User" ADD CONSTRAINT "User_id_site_fkey" FOREIGN KEY ("id_site") REFERENCES "Site"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ClientEmail" ADD CONSTRAINT "ClientEmail_id_client_fkey" FOREIGN KEY ("id_client") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Site" ADD CONSTRAINT "Site_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
