-- AlterTable
ALTER TABLE "Bill" ADD COLUMN     "FAC_HED" DECIMAL(4,2),
ADD COLUMN     "FAC_HEN" DECIMAL(4,2),
ADD COLUMN     "FAC_HFED" DECIMAL(4,2),
ADD COLUMN     "FAC_HFEN" DECIMAL(4,2),
ADD COLUMN     "FAC_HFOD" DECIMAL(4,2),
ADD COLUMN     "FAC_HFON" DECIMAL(4,2),
ADD COLUMN     "FAC_HOD" DECIMAL(4,2),
ADD COLUMN     "FAC_HON" DECIMAL(4,2);

-- AlterTable
ALTER TABLE "Tariff" ADD COLUMN     "FAC_ED" DECIMAL(4,2) NOT NULL DEFAULT 1.75,
ADD COLUMN     "FAC_EN" DECIMAL(4,2) NOT NULL DEFAULT 1.75,
ADD COLUMN     "FAC_FED" DECIMAL(4,2) NOT NULL DEFAULT 2,
ADD COLUMN     "FAC_FEN" DECIMAL(4,2) NOT NULL DEFAULT 2.5,
ADD COLUMN     "FAC_FOD" DECIMAL(4,2) NOT NULL DEFAULT 1.8,
ADD COLUMN     "FAC_FON" DECIMAL(4,2) NOT NULL DEFAULT 2.1,
ADD COLUMN     "FAC_OD" DECIMAL(4,2) NOT NULL DEFAULT 1,
ADD COLUMN     "FAC_ON" DECIMAL(4,2) NOT NULL DEFAULT 1.35,
ADD COLUMN     "UnitOfMesure_Facture" TEXT,
ADD COLUMN     "UnitOfMesure_Paysheet" TEXT;
